-- MySQL Script generated by MySQL Workbench
-- mar 03 may 2016 20:58:46 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_originalShop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_originalShop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_originalShop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_originalShop` ;

-- -----------------------------------------------------
-- Table `db_originalShop`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_originalShop`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(80) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_originalShop`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_originalShop`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(80) NULL,
  `cantidad` INT NULL,
  `precioCompra` DECIMAL NULL,
  `precioVenta` DECIMAL NULL,
  `fechaIngreso` DATE NULL,
  `id_sucursal` INT NULL,
  `id_proveedor` INT NULL,
  `id_tipoArticulo` INT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_originalShop`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_originalShop`.`sucursal` (
  `id_sucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_originalShop`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_originalShop`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_originalShop`.`tipoArticulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_originalShop`.`tipoArticulo` (
  `id_tipoArticulo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipoArticulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_originalShop`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_originalShop`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `id_sucursal` INT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_originalShop`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_originalShop`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `id_empleado` INT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_originalShop`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_originalShop`.`factura` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NULL,
  `id_empleado` INT NULL,
  `valorUnidad` DECIMAL NULL,
  `valorTotal` DECIMAL NULL,
  `valorPagar` DECIMAL NULL,
  PRIMARY KEY (`id_factura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_originalShop`.`detalleFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_originalShop`.`detalleFactura` (
  `id_detalleFactura` INT NOT NULL AUTO_INCREMENT,
  `id_factura` INT NULL,
  `id_producto` INT NULL,
  PRIMARY KEY (`id_detalleFactura`),
  UNIQUE INDEX `id_factura_UNIQUE` (`id_factura` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
